### ISSUE TITLE
Support for Additional Tags

### ISSUE THREAD

**Issue by JinLee794** [Azure/terraform-azurerm-openai#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently it appears that the tags are limited to `application_name` and `environment`.
https://github.com/Azure/terraform-azurerm-openai/blob/main/main.tf#L9

While looking to standardize tagging strategy based on customer's requirements, flexibility in the ability to provide custom tags would be essential.

### New or Affected Resource(s)/Data Source(s)

all tagged resources

### Potential Terraform Configuration

```hcl
perhaps adding a new variable "additional_tags":

variable "additional_tags" {
  default = {}
}

and on https://github.com/Azure/terraform-azurerm-openai/blob/main/main.tf#L9

  tags = merge(var.additional_tags, (var.default_tags_enabled ? {
    Application_Name = var.application_name
    Environment      = var.environment
  } : {})

(FYI haven't tested the function above works)
```

**Comment by zioproto** [comment]
Completed via #36
