### ISSUE TITLE
Support for deployment.scale.capacity

### ISSUE THREAD

**Issue by joecks** [Azure/terraform-azurerm-openai#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The [capacity](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_deployment#capacity) value is required to define the tokens per minute value.

It would be amazing if we could adjust that value. 

### New or Affected Resource(s)/Data Source(s)

terraform-azurerm-openai 

### Potential Terraform Configuration

```hcl
module "openai" {
  source                        = "../.."
  resource_group_name           = azurerm_resource_group.this.name
  location                      = azurerm_resource_group.this.location
  public_network_access_enabled = true
  deployment = {
    "text-davinci-003" = {
      name          = "text-davinci-003"
      model_format  = "OpenAI"
      model_name    = "text-davinci-003"
      model_version = "1"
      scale_type    = "Standard"
      # 10 = 10k token per minute
      capacity      = 10
    },
  }
  depends_on = [
    azurerm_resource_group.this
  ]
}
```

**Comment by zioproto** [comment]
Hello @joecks ,

I see the provider supports `capacity`:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_deployment#capacity

do you want to propose a PR for review ?

you need to add the `capacity` to the object in the `deployment` variable:
https://github.com/Azure/terraform-azurerm-openai/blob/8843bb4b07a595dd96d83457ac00988fd568fb81/variables.tf#L50-L76

and use it accordingly in the `azurerm_cognitive_deployment` resource:

https://github.com/Azure/terraform-azurerm-openai/blob/8843bb4b07a595dd96d83457ac00988fd568fb81/main.tf#L74-L89

please let us know if you want to submit a PR for review.

thanks

**Comment by joecks** [comment]
Yes, done.

**Comment by zioproto** [comment]
Completed via #45
