### ISSUE TITLE
Support for version update policy(deployments)

### ISSUE THREAD

**Issue by romanGarvis** [Azure/terraform-azurerm-openai#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, is it possible to add a new option for deployment resource, like version_upgrade_option?

Also, can you please release a new tag, as the last one was created in May last year?

### New or Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Potential Terraform Configuration

```hcl
variable "deployment" {
  type = map(object({
    name                    = string
    model_format            = string
    model_name              = string
    model_version           = string
    scale_type              = string
    rai_policy_name         = optional(string)
    capacity                = optional(number)
    version_upgrade_option  = optional(string)
  ...
}

resource "azurerm_cognitive_deployment" "this" {
  for_each = var.deployment
  ...
  version_upgrade_option  = each.value.version_upgrade_option
  ...
}
```

**Comment by zioproto** [comment]
Requires provider version v3.80.0

https://github.com/hashicorp/terraform-provider-azurerm/pull/22520

**Comment by zioproto** [comment]
@romanGarvis could you please test PR #59  ? Thanks

**Comment by romanGarvis** [comment]
works as expected

Thanks @zioproto
